.\" Hey, Emacs! This is -*-nroff-*- you know...
.\"
.\" genbrk.1: manual page for the genbrk utility
.\"
.TH GENBRK 1 "6 August 2005" "ICU MANPAGE" "ICU Manual"
.SH NAME
.B genbrk
\- generate a RuleBasedBreakIterator data file
.SH SYNOPSIS
.B genbrk
[
.BR "\-h\fP, \fB\-?\fP, \fB\-\-help"
]
[
.BR "\-V\fP, \fB\-\-version"
]
[
.BR "\-c\fP, \fB\-\-copyright"
]
[
.BR "\-v\fP, \fB\-\-verbose"
]
[
.BI "\-i\fP, \fB\-\-icudatadir" " directory"
]
[
.BI "\-d\fP, \fB\-\-destdir" " destination"
]
.IR bundle " \.\.\."
.SH DESCRIPTION
.B genbrk
generates RuleBasedBreakIterator data files (.brk files). .brk
files contain the precompiled rules for standard types
of iterators - word, line, sentence, etc.
.PP
The input rule file is a plain text file containing break rules
in the input format accepted by RuleBasedBreakIterators.  The
file can be encoded as utf-8, or utf-16 (either endian), or
in the default code page (platform dependent.).  utf encoded
files must include a BOM.
.SH OPTIONS
.TP
.BR "\-h\fP, \fB\-?\fP, \fB\-\-help"
Print help about usage and exit.
.TP
.BR "\-V\fP, \fB\-\-version"
Print the version of
.B genbrk
and exit.
.TP
.BR "\-v\fP, \fB\-\-verbose"
Display extra informative messages during execution.
.TP
.BI "\-d\fP, \fB\-\-destdir" " destination"
Set the destination directory to
.IR destination .
The default destination directory is specified by the environment variable
.BR ICU_DATA
or is the location set when ICU was built if
.B ICU_DATA
is not set.
.TP
.BI "\-i\fP, \fB\-\-icudatadir" " directory"
Look for any necessary ICU data files in
.IR directory .
For example, when processing collation overrides, the file
.B ucadata.dat
must be located.
The default ICU data directory is specified by the environment variable
.BR ICU_DATA .
