.\" Hey, Emacs! This is -*-nroff-*- you know...
.\"
.\" icuswap.8: manual page for the icuswap utility
.\"
.TH ICUSWAP 8 "6 August 2005" "ICU MANPAGE" "ICU Manual"
.SH NAME
.B icuswap
\- generate a RuleBasedBreakIterator data file
.SH SYNOPSIS
.B icuswap
[
.BR "\-h\fP, \fB\-?\fP, \fB\-\-help"
]
[
.BR "\-tl|\-tb|\-te\|\-\-type=b|\.\.\.
]
.IR infile
.IR outfile
.SH DESCRIPTION
.B icuswap
takes an ICU data file and "swaps" it, that is, changes its
platform properties between big-/little-endianness and ASCII/EBCDIC charset
families.
.PP
The modified data file is written to a new file.
Useful as an install-time tool for shipping only one flavor of ICU data
and preparing data files for the target platform.
Will not work with data DLLs (shared libraries).
.SH OPTIONS
.TP
.BR "\-h\fP, \fB\-?\fP, \fB\-\-help"
Print help about usage and exit.
.TP
.BI "\-tl|\-tb|\-te\|\-\-type=b\|\.\.\,"
Set the type to little endian, big endian, or EBCDIC.
